version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "krailo-vault/worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "krailo-vault/cli"
    schedule:
      interval: "weekly"
