name = "petition-tracker"
main = "src/index.js"
compatibility_date = "2024-02-23"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "PETITION_KV"
id = "a46a0884847e42be8d77c6b8310ffbd3"